name: release

on:
  pull_request:
    branches: [master]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Unshallow
        run: echo $PP > PASSPHRASE
        env: 
          PP: ${{ secrets.PASSPHRASE }}

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: PASSPHRASE
