name: release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
env:
  GITHUB_TOKEN: ${{ secrets.GORELEASE_GITHUB_TOKEN }}

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v1

      - name: Set up Golang
        uses: actions/setup-go@v1

      - name: Release Application
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
